var hello=require("./hello1");
hello();//hello 1 ...

var hello2=require('./hello2').sayHello;
hello2();//hello 2...

var hello3=require('./hello3');
hello3.sayHello();//heello world 3...
hello3.message="change hello 3....";
var hello3_2=require('./hello3');
hello3_2.sayHello();//change hello 3....

var hello4=require('./hello4');
var hello44=new hello4();
hello44.sayHello();//heello world 4...

var hello5=require('./hello5').sayHello;
hello5();//say hello 5...
var hello55=require('./hello5');
hello55.sayHello();//say hello 5...
console.log(hello55.message);//undefined
console.log(hello55.note);//say hello 5...